name: Realização de deploy no k8s

on:
  workflow_call:
    inputs:
      environment-name:
        type: string
        required: true
      environment-url:
        type: string
        required: true        

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}
    steps:
      - name: Obtendo conteúdo do repo
        uses: actions/checkout@v4

      - name: Configurando acesso ao cluster k8s
        uses: azure/k8s-set-context@v4
        with: 
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Update Deployment
        run: "sed -i 's/host: homologacao.rangelcr.com/host: ${{ vars.BASE_URL }}/g' k8s/deployment.yaml"
      
      - name: Realizando o deploy
        uses: Azure/k8s-deploy@v5
        with:
          namespace: ${{ vars.K8S_NAMESPACE }}
          manifests: |
            k8s/deployment.yaml
          images: |
            rangelcr/pipe-desafio:v${{ github.run_number }}


