name: Pipeline desafio
run-name: Pipeline executada por ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build dotnet
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo conteúdo do repo
        uses: actions/checkout@v4
      - name: Instalando .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execução do comando de build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    uses: RangelCR/desafio-cicd-01/.github/workflows/testes.yaml@main
    secrets: inherit


  release:
    needs: [testes]
    name: Criação de imagem docker
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo conteúdo do repo
        uses: actions/checkout@v4
      - name: Analisando Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile
      - name: Autenticando no docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construção e push da imagem
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          push: true
          tags: |
            rangelcr/pipe-desafio:v${{ github.run_number }}
            rangelcr/pipe-desafio:latest
      - name: Realizando scan de vulnerabilidades da imagem com trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: rangelcr/pipe-desafio:latest
          format: 'table'
          vuln-type: 'os,library'          
          severity: 'CRITICAL,HIGH'       

  deploy-hml:
    needs: [release]
    uses: RangelCR/desafio-cicd-01/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      environment-name: hml
      environment-url: http://homologacao.rangelcr.com


  test-e2e:
    name: Teste End to End
    runs-on: ubuntu-latest
    needs: [deploy-hml]
    environment:
      name: hml
    container:
      image: fabricioveronez/webdriver-dotnet:chrome
      env:
        BASE_URL: "http://${{ vars.BASE_URL }}"
    steps:
      - name: Obtendo conteúdo do repo
        uses: actions/checkout@v4
      - name: Execução de teste de E2E
        working-directory: ./src
        run: dotnet test ./Review-Filmes.Test.EndToEnd/Review-Filmes.Test.EndToEnd.csproj    

      

  deploy-prd:
    needs: [teste-e2e]
    uses: RangelCR/desafio-cicd-01/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      environment-name: prd
      environment-url: http://producao.rangelcr.com      

        
